version: "3.9"

services:
  db:
    image: postgres:15
    container_name: dzvolunteer-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: malak123
      POSTGRES_DB: dzvolunteerdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./BACKEND
    container_name: dzvolunteer-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:malak123@db:5432/dzvolunteerdb
    depends_on:
      - db

  frontend:
    build: ./FRONTEND
    container_name: dzvolunteer-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
